# Generated by Django 5.1.2 on 2025-03-08 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='time',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('BiWeekly', 'BiWeekly'), ('Monthly', 'Monthly')], default='BiWeekly', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spending',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=10), blank=True, default=list, size=None),
        ),
    ]
