# Generated by Django 5.1.2 on 2025-03-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_time_allowance_schedules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='schedules',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='biweekly', max_length=10),
        ),
    ]
