# Generated by Django 5.1.2 on 2025-03-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_allowance_set_allowance_alter_expense_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='schedules',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='Biweekly', max_length=10),
        ),
    ]
